version: '3'

services:
  infrared:
    build: .
    container_name: infrared
    restart: "no"
    ports:
      - 8123:8080
    volumes:
      - "../config/:/configs"
    environment:
        INFRARED_CONFIG_PATH: ./configs/
