version: '3'

services:
  infrared:
    build: .
    container_name: infrared
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /your/path/here:/configs
    environment:
        INFRARED_CONFIG_PATH: ./configs/
