DomainName: "kuen.haveachin.de"
ListenTo: ":25565"
ProxyTo: ":1337"
DisconnectMessage: "Sorry §e$username§r, but the server is §osleeping§r right now."
Timeout: "13m37s"
Docker:
    ContainerID: "a87418df4b57487b7d0968cac28fd7d1537c5dac9e58059eaece47c7e7b1f5e3"
    Portainer:
        Address: "localhost:9000"
        EndpointID: "1"
        Username: "mctest"
        Password: "Ichwambo007"
Placeholder:
    Version: "1.15.2"
    Protocol: 578
    Motd: "Server is currently sleeping"
    MaxPlayers: 20
    PlayersOnline: 2
    Players:
        - Name: "Steve"
          ID: "8667ba71-b85a-4004-af54-457a9734eed7"
        - Name: "Alex"
          ID: "ec561538-f3fd-461d-aff5-086b22154bce"